# Generated by Django 3.1 on 2023-05-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_employee_user'),
        ('assets', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('Device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.device')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.comapany_name')),
            ],
        ),
    ]
